name: Publish Package

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

permissions: 
  packages: write
  contents: read

jobs:
  build:

    runs-on: [self-hosted, nonroot]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7
      - name: set beta metadata (PR)
        if: startsWith(github.ref, 'refs/tags/v') != true
        run: echo "APPEND=beta-${{ steps.short-sha.outputs.sha }}" >> $GITHUB_ENV
      - name: run minver
        id: version
        uses: Stelzi79/action-minver@3.0.1
        with:
          default-pre-release-phase: ${{ env.APPEND }}
          tag-prefix: v
          minver-version: 4.2.0
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release -p:Version=${{ steps.version.outputs.version }} --no-restore
      - name: Run Tests
        run: dotnet test
      - name: Pack
        run: dotnet pack --configuration Release --no-build -p:Version=${{ steps.version.outputs.version }}
      - name: Push
        run: dotnet nuget push **EPPlus.HTML/bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/urbansportsclub/index.json --skip-duplicate --no-symbols
